### ISSUE TITLE
NotReadableError: Could not start video source

### ISSUE THREAD

**Issue by alexaltair** [dspeyer/ritualEngine#90] opened 2020-12-06 05:07 UTC
![Screenshot from 2020-12-05 21-06-36](https://user-images.githubusercontent.com/4567419/101272092-e2a61500-373d-11eb-8a1d-34ba3313433e.png)

**Comment by alexaltair** [comment] 2020-12-06 05:08
This is upon loading the page `https://secularsolsticebeta.com/test/partake`

**Comment by alexaltair** [comment] 2020-12-06 05:35
This was probably due to me having zoom open at the same time. (Ubuntu 20.04)

**Comment by taymonbeal** [comment] 2020-12-13 06:09
Duplicate of #47.

**Closed as completed by taymonbeal** 2020-12-13 06:09 UTC
