### ISSUE TITLE
Bucket Brigade drops future events on reconnection, impacting pre-canned lyrics

### ISSUE THREAD

**Issue by gwillen** [dspeyer/ritualEngine#225] opened 2020-12-19 09:10 UTC
see https://github.com/gwillen/solstice-audio-test/issues/123

I am thinking about what the right way to handle this at an architectural level is, ideally making sure that events fire better-late-than-never.

**Comment by taymonbeal** [comment] 2020-12-19 09:10
Duplicate of #224.

**Closed as completed by taymonbeal** 2020-12-19 09:10 UTC
