### ISSUE TITLE
Crash after re-opening a ritual on a twilio tab

### ISSUE THREAD

**Issue by Raemon** [dspeyer/ritualEngine#85] opened 2020-12-05 23:37 UTC
This was on Taymons' betatesting server. It was running off a recently updated branch.

```
TwilioError: Room not found
    at RoomNotFoundError.TwilioError (https://media.twiliocdn.com/sdk/js/video/releases/2.8.0/twilio-video.min.js:54:8557)
    at new RoomNotFoundError (https://media.twiliocdn.com/sdk/js/video/releases/2.8.0/twilio-video.min.js:53:18602)
    at createTwilioError (https://media.twiliocdn.com/sdk/js/video/releases/2.8.0/twilio-video.min.js:53:7258)
    at TwilioConnection.handleMessage (https://media.twiliocdn.com/sdk/js/video/releases/2.8.0/twilio-video.min.js:48:7689)
    at TwilioConnection.emit (https://media.twiliocdn.com/sdk/js/video/releases/2.8.0/twilio-video.min.js:57:3991)
    at TwilioConnection._handleMessage (https://media.twiliocdn.com/sdk/js/video/releases/2.8.0/twilio-video.min.js:50:20337)
    at WebSocket.<anonymous> (https://media.twiliocdn.com/sdk/js/video/releases/2.8.0/twilio-video.min.js:50:17467)```

in console.log:

![image](https://user-images.githubusercontent.com/3246710/101267701-85e03580-3710-11eb-9efd-b1825f0c7d4a.png)

**Comment by taymonbeal** [comment] 2020-12-13 06:21
Duplicate of #118.

**Closed as completed by taymonbeal** 2020-12-13 06:21 UTC
