### ISSUE TITLE
Crashed 

### ISSUE THREAD

**Issue by Raemon** [dspeyer/ritualEngine#96] opened 2020-12-06 20:54 UTC
check@https://secularsolstice2020.org/widgets/BucketSinging/lib.js:20:11
concat_chunks@https://secularsolstice2020.org/widgets/BucketSinging/audiochunk.js:215:18
handle_message@https://secularsolstice2020.org/widgets/BucketSinging/app.js:838:32
handle_message@https://secularsolstice2020.org/widgets/BucketSinging/app.js:527:10

**Comment by taymonbeal** [comment] 2020-12-13 08:25
I'm going to assume that this is a duplicate of #103.

**Closed as completed by taymonbeal** 2020-12-13 08:25 UTC
