### ISSUE TITLE
Stress Test Error

### ISSUE THREAD

**Issue by EEdwardsA** [dspeyer/ritualEngine#103] opened 2020-12-06 22:11 UTC
After my wife did sound and singing calibration and was waiting for the singing to start, lyrics popped up briefly, then the whole page crashed for her and displayed the following error:

Error: Cannot switch from audio chunk back to placeholder chunk
    at check (https://secularsolstice2020.org/widgets/BucketSinging/lib.js:20:11)
    at concat_chunks (https://secularsolstice2020.org/widgets/BucketSinging/audiochunk.js:215:13)
    at EventTarget.handle_message (https://secularsolstice2020.org/widgets/BucketSinging/app.js:847:19)
    at EventTarget.dispatchEvent (<anonymous>)
    at EventTarget.handle_message (https://secularsolstice2020.org/widgets/BucketSinging/app.js:527:10)

Related: gwillen/solstice-audio-test#99

**Comment by gwillen** [comment] 2020-12-13 06:35
I believe that #113 is a dupe of this, and should be closed in favor of this (since that one has the problem that Ray was getting crappy backtraces in Firefox, so this one has more details.)

**Comment by taymonbeal** [comment] 2020-12-13 09:35
@Raemon, is there any further context on #113? If not I think we'll have to close this as non-reproable (and hope it comes up in chaos testing in a few days, if it hasn't been fixed already).

**Closed as completed** 2020-12-13 15:03 UTC
