### ISSUE TITLE
BucketSinging error

### ISSUE THREAD

**Issue by Raemon** [dspeyer/ritualEngine#113] opened 2020-12-08 02:28 UTC
check@https://secularsolstice2020.org/widgets/BucketSinging/lib.js:20:11
concat_chunks@https://secularsolstice2020.org/widgets/BucketSinging/audiochunk.js:215:18
handle_message@https://secularsolstice2020.org/widgets/BucketSinging/app.js:847:32
handle_message@https://secularsolstice2020.org/widgets/BucketSinging/app.js:527:10

Blocked by: gwillen/solstice-audio-test#98

**Comment by taymonbeal** [comment] 2020-12-13 09:32
Duplicate of #103.

**Closed as completed by taymonbeal** 2020-12-13 09:32 UTC
