### ISSUE TITLE
Crash when changing slides-while-calibrating

### ISSUE THREAD

**Issue by Raemon** [dspeyer/ritualEngine#123] opened 2020-12-12 02:05 UTC
Happened when I:
a) started calibrating (as lead)
b) moved to next slide
c) I finished calibrating on the next side, apparently while the backing track was loading
d) after calibrating I got ANOTHER calibration box
e) backing track + video appeared to load normally
f) sometime in the middle of the backing track I received the following crash (i think the backing track kept working, not sure if bucket brigade was otherwise working)

TypeError: Cannot read property '0' of undefined
    at BucketSinging.handleLyric (https://secularsolstice2020.org/widgets/BucketSinging.js:309:33)
    at HTMLDivElement.<anonymous> (https://secularsolstice2020.org/widgets/BucketSinging.js:292:28)
    at HTMLDivElement.dispatch (https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js:2:43090)
    at HTMLDivElement.v.handle (https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js:2:41074)

![image](https://user-images.githubusercontent.com/3246710/101969577-ddcbe000-3bd9-11eb-985a-6976a37cd8e8.png)

**Comment by taymonbeal** [comment] 2020-12-13 06:18
Duplicate of #121.

**Closed as completed by taymonbeal** 2020-12-13 06:18 UTC
